version: '3'
services:
    quasar:
        build:
            context: ./QuasarDock
            dockerfile: Dockerfile.Quasar
        command: quasar dev
        tty: true
        volumes:
            - .:/mnt
        working_dir: /mnt
        ports:
            - "8080:8080"
