version: '3'
services:
    quasar:
        build:
            context: .
        command: /bin/bash
        tty: true
        volumes:
            - .:/mnt
        working_dir: /mnt
        ports:
            - "8080:8080"
