version: '3'
services:
    quasar:
        build:
            context: ./
            dockerfile: Dockerfile.Quasar
        image: quasardock/quasardock
        command: quasar dev
        tty: true
        volumes:
            - ..:/mnt
        working_dir: /mnt
        ports:
            - "8080:8080"
